### ISSUE TITLE
pooch seems to be also a required dependency

### ISSUE THREAD

**Issue by boltomli** [bshall/ZeroSpeech#11]
I've no idea why it's used in some packages but not installed by default.

**Comment by bshall** [comment]
Hi @boltomli,

I'm guessing that it's librosa that requires pooch? I know that they recently swapped to using pooch for their v0.8 but I don't think it's a requirement for v0.7.2 (which is specified in `requirements.txt`). Would you mind posting the version of the package that requires pooch?

**Comment by boltomli** [comment]
Thanks for the hint, yes it should be the problem, librosa in system was used at first which is 0.8.0. Virtual environment is fine with specified version.
