### ISSUE TITLE
Vector dimension does not match other files

### ISSUE THREAD

**Issue by liu-x-p** [bshall/ZeroSpeech#15]
Thanks for sharing your work.
I tried to reproduction it, but when I perform the zs2020evaluate for the auxiliary embedding, it reports error

```
Traceback (most recent call last):
  File "/home/speech/anaconda3/envs/zerospeech2020/bin/zerospeech2020-evaluate", line 33, in <module>
    sys.exit(load_entry_point('zerospeech2020==0.2', 'console_scripts', 'zerospeech2020-evaluate')())
  File "/home/speech/anaconda3/envs/zerospeech2020/lib/python3.8/site-packages/zerospeech2020-0.2-py3.8.egg/zerospeech2020/evaluation/main.py", line 197, in main
  File "/home/speech/anaconda3/envs/zerospeech2020/lib/python3.8/site-packages/zerospeech2020-0.2-py3.8.egg/zerospeech2020/evaluation/evaluation_2019.py", line 60, in evaluate
  File "/home/speech/anaconda3/envs/zerospeech2020/lib/python3.8/site-packages/zerospeech2020-0.2-py3.8.egg/zerospeech2020/evaluation/evaluation_2019.py", line 60, in <dictcomp>
  File "/home/speech/anaconda3/envs/zerospeech2020/lib/python3.8/site-packages/zerospeech2020-0.2-py3.8.egg/zerospeech2020/evaluation/evaluation_2019.py", line 102, in _evaluate_single
  File "/home/speech/anaconda3/envs/zerospeech2020/lib/python3.8/site-packages/zerospeech2020-0.2-py3.8.egg/zerospeech2020/evaluation/bitrate.py", line 81, in bitrate
  File "/home/speech/anaconda3/envs/zerospeech2020/lib/python3.8/site-packages/zerospeech2020-0.2-py3.8.egg/zerospeech2020/read_2019_features.py", line 93, in read_all
  File "/home/speech/anaconda3/envs/zerospeech2020/lib/python3.8/site-packages/zerospeech2020-0.2-py3.8.egg/zerospeech2020/read_2019_features.py", line 22, in log_or_raise
zerospeech2020.read_2019_features.ReadZrsc2019Exception: Vector dimension does not match other files: S011_2504494747.txt
```
I checked the output files in test and auxiliary_embedding1, it did have different dims. But I'm not sure how to set the parameters of the auxiliary embedding and how to change it.
Hope you can answer this question.

**Comment by bshall** [comment]
Hi @liu-x-p,

Are you running the evaluation on the pretrained model? I've just re-run the encode and evaluate scripts on my side and they seem to work fine. Could you send the exact commands you used with `encode.py` and `zerospeech2020-evaluate`?

**Comment by liu-x-p** [comment]
@bshall Thank you for your reply.
The commands I used are
`python encode.py checkpoint=checkpoints/2019english/model.ckpt-200000.pt out_dir=test dataset=2019/english`
`zerospeech2020-evaluate 2019 -j 2 -d cosine --dataset ./data ./submissionzsmyuando200k -o submissionzsmyuando200k/2019.json`
The model is trained following your instruction. The model.ckpt-200000.pt was trained with resuming from early ckpt, but I also tried the model without resume, it also have tis problem.

**Comment by bshall** [comment]
No problem @liu-x-p,

The `zerospeech2020-evaluate` script expects the directory structure to look like `submission/2019/english/test` so could you try:

`python encode.py checkpoint=checkpoints/2019english/model.ckpt-200000.pt out_dir=submission/2019/english/test dataset=2019/english`

and then run:

`zerospeech2020-evaluate 2019 -j 2 -d cosine --dataset ./data submission/`

**Comment by liu-x-p** [comment]
@bshall But I moved the test files to the correct directory before evaluate. And I can really run the evaluate script if I only evaluate,the `test` files in ` submission/2019/english/` , but once I move the `auxiliary_embedding1` directory into it and run evaluate, it will go wrong.

**Comment by bshall** [comment]
If you run:

`python encode.py checkpoint=checkpoints/2019english/model.ckpt-200000.pt out_dir=submission/2019/english/test dataset=2019/english save_auxiliary=true`

It will put everything in the correct directory structure (including the auxiliary embeddings). Then you can just run:

`zerospeech2020-evaluate 2019 -j 2 -d cosine --dataset ./data submission/`

and it'll evaluate everything (no need to copy any of the folders). Hopefully that works for you?

**Comment by liu-x-p** [comment]
@bshall It still report that error.  :(
Maybe I should just not use the Auxiliary embedding

**Comment by bshall** [comment]
That's strange. Could you attach the `S011_2504494747.txt` file and the `S011_2504494747.mel.npy` file so I can try to figure out what's going wrong?

**Comment by liu-x-p** [comment]
[Uploading S011_2504494747_auxiliary.txt…]()
Thank you for your help. I uploaded the S011_2504494747.txt files for both `test` and  `auxiliary_embedding1`

**Comment by liu-x-p** [comment]
Thank you for your help. I will uplod
[Uploading S011_2504494747_auxiliary.txt…]()
d the S011_2504494747.txt files for both test and auxiliary_embedding1

**Comment by liu-x-p** [comment]
Thank you for your help. I uploaded the S011_2504494747.txt files for both test and auxiliary_embedding1
[S011_2504494747_auxiliary.txt](https://github.com/bshall/ZeroSpeech/files/5378348/S011_2504494747_auxiliary.txt)
[S011_2504494747_test.txt](https://github.com/bshall/ZeroSpeech/files/5378349/S011_2504494747_test.txt)

**Comment by liu-x-p** [comment]
[S011_2504494747.mel.zip](https://github.com/bshall/ZeroSpeech/files/5378354/S011_2504494747.mel.zip)

**Comment by bshall** [comment]
Thanks @liu-x-p, I think you might be using an altered version of `encode.py`. Can you compare your's against lines 39-45 [here](https://github.com/bshall/ZeroSpeech/blob/master/encode.py#L39-L45)? It seems like your auxiliary embeddings are hooking on to a different layer in the encoder (and don't use transpose to get the correct ordering of dimensions).

**Comment by liu-x-p** [comment]
@bshall  They're the same. 
But I changed some layers in the model, could that be the reason? I didn't change the parameters in the code.

**Comment by bshall** [comment]
Yip, that's the problem. If you want to change layers you'll also have to change where the forward hook is registered. You need to register it on the layer where you want to extract the auxiliary embeddings and you need to make sure the dimensions are ordered correctly i.e. whether to transpose or not.

**Comment by liu-x-p** [comment]
Thank you! @bshall  
I haven't use hook, and I searched for it and checked the `encode.py` . It did point to a different layer's output, and I changed it then it works.

**Comment by bshall** [comment]
No problem @liu-x-p.
