### ISSUE TITLE
ImportError when trying to compute ABX score

### ISSUE THREAD

**Issue by bhigy** [bshall/ZeroSpeech#7]
Hi,

I am trying to compute ABX score on the pretrained model, english version. Using the command from the README, I first got following error:
`ModuleNotFoundError: No module named 'numba.decorators'`
This is apparently a solved bug in librosa but the fix hasn't made it into a release yet. I solved it by putting strict requirements for all packages in `requirements.txt` (`==` instead of `>=`, which by the way is probably better for reproducibility of results).

Now I get another error:
`ImportError: cannot import name 'Config' from 'omegaconf'`
I fear it might again be a version specific issue. Could you provide the exact version you use for each package (`pip list`)?

**Comment by bshall** [comment]
Yeah, seems like a version problem. I'll update the `requirements.txt` with strict version numbers. For now the relevant package versions are:

1. librosa 0.7.2
2. hydra-core 0.11.3
3. omegaconf 1.4.1

Thanks for reporting these issues @bhigy, it's really helpful having someone try to reproduce things in a different environment.

**Comment by omry** [comment]
This is one of the breaking changes in OmegaConf 2.0 and Hydra 1.0.

Hydra 1.0.0rc1 is a release candidate and I am encouraging you to upgrade to it.

**Comment by bhigy** [comment]
> Yeah, seems like a version problem. I'll update the `requirements.txt` with strict version numbers. For now the relevant package versions are:
> 
>     1. librosa 0.7.2
> 
>     2. hydra-core 0.11.3
> 
>     3. omegaconf 1.4.1
> 
> 
> Thanks for reporting these issues @bhigy, it's really helpful having someone try to reproduce things in a different environment.

It seems that numba version also needs to be specified. I will make a pull request.

**Comment by NiNicoder** [comment]
For me, update the version of  hydra-core works.
